---
apiVersion: v1
kind: Namespace
metadata:
  name: appuio-acm-sample-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: appuio-acm-sample-app
  namespace: appuio-acm-sample-app
spec:
  type: GitHub
  pathname: https://github.com/appuio/acm-example.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: appuio-acm-sample-app
  namespace: appuio-acm-sample-app
  annotations:
    apps.open-cluster-management.io/git-path: sample-app
  labels:
    app: appuio-acm-sample-app
spec:
  channel: appuio-acm-sample-app/appuio-acm-sample-app
  name: appuio-acm-sample-app
  placement:
    clusters:
    - name: ocp3-cloudscale-staging
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: appuio-acm-sample-app
  name: appuio-acm-sample-app
  namespace: appuio-acm-sample-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: appuio-acm-sample-app
